#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OSINT-REILLY | Block 2 — Semantic Counter-Collector (Red Teaming Contour)
Path: core_intelligence/data_collection/semantic_collector.py
Line Length Limit: 100 characters

Cognitive architecture:
  For every SEMANTIC search task from ActionProgram, the collector performs a
  DUAL sweep — direct evidence ("arguments FOR") and a mirrored counter-sweep
  ("arguments AGAINST") generated by the LLM router.
  This eliminates Confirmation Bias before data reaches Block 4 (Analytics).

Integration contract:
  INPUT  ← ActionProgram dict (Block 1 output)
  OUTPUT → Structured JSON cache file + in-memory dict for Block 4
"""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Optional

from .brightdata_client import BrightDataClient
from core_intelligence.router import ReillyLlmRouter

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

# Default directory for raw semantic cache files
DEFAULT_CACHE_DIR = "./state/semantic_cache"

# SearchType marker we filter for in this module
SEMANTIC_TYPE = "SEMANTIC"

# ─────────────────────────────────────────────────────────────────────────────
# Red Teaming prompt (kept here, not in prompts.py — collector owns its logic)
# ─────────────────────────────────────────────────────────────────────────────

_RED_TEAM_SYSTEM = """
You are the OSINT-REILLY Red Teaming Engine.
Your sole task: invert the SEARCH INTENT of each given Google Dork or search query.

Rules:
- Produce exactly ONE counter-query per input query.
- The counter-query must search for OPPOSITE evidence:
    if original seeks "deficit/shortage/failure" → counter seeks "surplus/growth/success"
    if original seeks "sanctions/restrictions"   → counter seeks "bypass/workaround/supply"
    if original seeks "military buildup"         → counter seeks "demobilisation/reduction"
- Preserve site: / filetype: / intitle: operators from the original where possible.
- Keep the same language as the original query.
- Do NOT add explanations. Return ONLY a JSON array of counter-query strings,
  in the same order as the input list. No markdown, no preamble.

Example input:  ["site:gov.ru \"тендер\" \"Уралвагонзавод\" дефіцит 2024"]
Example output: ["site:gov.ru \"модернізація\" \"Уралвагонзавод\" розширення 2024"]
"""

_RED_TEAM_USER_TEMPLATE = (
    "Generate counter-queries for the following list:\n\n{queries_json}"
)


# ─────────────────────────────────────────────────────────────────────────────
# SemanticCollector
# ─────────────────────────────────────────────────────────────────────────────

class SemanticCollector:
    """
    Семантичний контр-колектор Блоку 2.

    Реалізує подвійний збір для усунення Confirmation Bias:
      1. Прямий пул  — оригінальні dorks з ActionProgram (аргументи «ЗА»)
      2. Дзеркальний пул — LLM-інвертовані контр-dorks (аргументи «ПРОТИ»)

    Обидва пули зберігаються у спільній структурі і передаються до Block 4.
    """

    def __init__(
        self,
        bd_client: BrightDataClient,
        router: ReillyLlmRouter,
        cache_dir: str = DEFAULT_CACHE_DIR,
    ):
        """
        Args:
            bd_client:  Ініціалізований BrightDataClient (Блок 2 — «руки»).
            router:     Ініціалізований ReillyLlmRouter  (Блок 1 — «мізки»).
            cache_dir:  Шлях до папки для збереження сирих JSON-кешів.
        """
        self.bd_client = bd_client
        self.router    = router
        self.cache_dir = cache_dir
        os.makedirs(self.cache_dir, exist_ok=True)
        logger.info("[SemanticCollector] Ready | cache_dir=%s", self.cache_dir)

    # ─────────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────────

    def collect_semantic_pipeline(
        self,
        action_program: dict,
        country: str = "us",
        language: str = "en",
        save_cache: bool = True,
    ) -> dict:
        """
        Головний конвеєр подвійного семантичного збору.

        Args:
            action_program: Словник ActionProgram.to_dict() з виходу Блоку 1.
            country:        ISO-код країни для геолокованої пошукової видачі.
            language:       Мова результатів SERP.
            save_cache:     Якщо True — зберігає результат у JSON-файл у cache_dir.

        Returns:
            Структурований словник з direct_results + counter_results на кожен dork.
            Готовий до передачі в Block 4 (Analytics) без додаткової обробки.
        """
        raw_query   = action_program.get("raw_query", "")
        search_tasks = action_program.get("search_tasks", [])

        logger.info(
            "[SemanticCollector] Pipeline START | query=%.70s | tasks=%d",
            raw_query, len(search_tasks),
        )

        # ── Крок 1: Фільтруємо лише SEMANTIC таски ───────────────────────────
        semantic_tasks = [
            t for t in search_tasks
            if t.get("search_type") == SEMANTIC_TYPE
        ]

        if not semantic_tasks:
            logger.warning(
                "[SemanticCollector] No SEMANTIC tasks found in ActionProgram. "
                "Returning empty result."
            )
            return self._build_output(raw_query, [])

        logger.info(
            "[SemanticCollector] Found %d SEMANTIC task(s).", len(semantic_tasks)
        )

        # ── Крок 2: Збираємо всі initial_queries з усіх SEMANTIC тасків ──────
        all_dorks: list[str] = []
        for task in semantic_tasks:
            all_dorks.extend(task.get("initial_queries", []))

        if not all_dorks:
            logger.warning("[SemanticCollector] SEMANTIC tasks have no initial_queries.")
            return self._build_output(raw_query, [])

        logger.info("[SemanticCollector] Total dorks to process: %d", len(all_dorks))

        # ── Крок 3: Red Teaming — генеруємо контр-запити через LLM ──────────
        counter_dorks = self.generate_counter_dorks(all_dorks)

        # ── Крок 4: Подвійний SERP-збір (прямий + дзеркальний) ───────────────
        semantic_data = self._run_dual_sweep(
            all_dorks, counter_dorks, country, language
        )

        # ── Крок 5: Пакетування та збереження ────────────────────────────────
        output = self._build_output(raw_query, semantic_data)

        if save_cache:
            cache_path = self._save_to_cache(output)
            output["cache_file"] = cache_path

        ok_pairs = sum(1 for s in semantic_data if s.get("direct_results"))
        logger.info(
            "[SemanticCollector] Pipeline COMPLETE ✅ | "
            "pairs=%d | successful_direct=%d",
            len(semantic_data), ok_pairs,
        )
        return output

    def generate_counter_dorks(self, original_queries: list[str]) -> list[str]:
        """
        Використовує ReillyLlmRouter для генерації дзеркальних контр-запитів.

        Принцип Red Teaming:
          "Уралвагонзавод дефіцит металу" → "Уралвагонзавод постачання розширення"
          Аргумент «ЗА» → Аргумент «ПРОТИ»

        Args:
            original_queries: Список вхідних dorks / пошукових запитів.

        Returns:
            Список контр-запитів тієї ж довжини. При збої LLM — повертає
            безпечні fallback-інверсії без переривання пайплайну.
        """
        if not original_queries:
            return []

        logger.info(
            "[RedTeam] Generating %d counter-dorks via LLM router...",
            len(original_queries),
        )

        queries_json = json.dumps(original_queries, ensure_ascii=False)
        user_message = _RED_TEAM_USER_TEMPLATE.format(queries_json=queries_json)

        try:
            raw_text = self.router.execute_query(
                task_type="semantic_propaganda",  # Groq Llama — швидкий семантичний контур
                system_prompt=_RED_TEAM_SYSTEM,
                user_prompt=user_message,
            )
            counter_dorks = self._parse_counter_dorks(raw_text, original_queries)

        except Exception as exc:
            logger.error(
                "[RedTeam] LLM router failure: %s — applying lexical fallback.", exc
            )
            counter_dorks = self._lexical_fallback(original_queries)

        # Гарантуємо рівність довжин: пайплайн завжди отримує пару на кожен dork
        if len(counter_dorks) != len(original_queries):
            logger.warning(
                "[RedTeam] Length mismatch (got %d, expected %d). "
                "Padding with fallback.",
                len(counter_dorks), len(original_queries),
            )
            counter_dorks = self._align_length(
                counter_dorks, original_queries
            )

        for orig, counter in zip(original_queries, counter_dorks):
            logger.debug("[RedTeam] PAIR | orig=%.50s | counter=%.50s", orig, counter)

        logger.info("[RedTeam] ✅ %d counter-dorks ready.", len(counter_dorks))
        return counter_dorks

    # ─────────────────────────────────────────────────────────────────────────
    # Internal helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _run_dual_sweep(
        self,
        direct_dorks: list[str],
        counter_dorks: list[str],
        country: str,
        language: str,
    ) -> list[dict]:
        """
        Виконує подвійний SERP-збір для кожної пари (original, counter).
        Повертає список об'єктів із розділеними пулами результатів.
        """
        results = []

        for idx, (orig, counter) in enumerate(
            zip(direct_dorks, counter_dorks), 1
        ):
            logger.info(
                "[DualSweep] Pair %d/%d | direct: %.55s",
                idx, len(direct_dorks), orig,
            )

            # Прямий збір — аргументи «ЗА»
            direct_batch = self.bd_client.fetch_serp(
                queries=[orig],
                country=country,
                language=language,
            )
            direct_entry = direct_batch[0] if direct_batch else {}

            logger.info(
                "[DualSweep] Pair %d/%d | counter: %.55s",
                idx, len(direct_dorks), counter,
            )

            # Дзеркальний збір — аргументи «ПРОТИ»
            counter_batch = self.bd_client.fetch_serp(
                queries=[counter],
                country=country,
                language=language,
            )
            counter_entry = counter_batch[0] if counter_batch else {}

            results.append({
                "original_dork":  orig,
                "counter_dork":   counter,
                "direct_results":  direct_entry.get("results", []),
                "counter_results": counter_entry.get("results", []),
                "direct_status":   direct_entry.get("status", "error"),
                "counter_status":  counter_entry.get("status", "error"),
            })

        return results

    @staticmethod
    def _build_output(raw_query: str, semantic_data: list[dict]) -> dict:
        """Збирає фінальний вихідний словник для збереження та передачі в Block 4."""
        return {
            "raw_query":    raw_query,
            "collected_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "semantic_data": semantic_data,
        }

    def _save_to_cache(self, output: dict) -> str:
        """
        Записує вихідний словник у JSON-файл у cache_dir.
        Ім'я файлу містить UTC-мітку часу для однозначної ідентифікації сесії.
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename  = f"semantic_{timestamp}.json"
        filepath  = os.path.join(self.cache_dir, filename)

        try:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(output, f, ensure_ascii=False, indent=2)
            logger.info("[SemanticCollector] Cache saved → %s", filepath)
        except OSError as exc:
            logger.error("[SemanticCollector] Failed to save cache: %s", exc)
            return ""

        return filepath

    # ── Red Teaming parsing helpers ───────────────────────────────────────────

    @staticmethod
    def _parse_counter_dorks(
        raw_text: str,
        original_queries: list[str],
    ) -> list[str]:
        """
        Безпечно парсить JSON-масив контр-запитів з відповіді LLM.
        Очищає markdown-феніси, якщо модель додала їх всупереч інструкції.
        """
        cleaned = raw_text.replace("```json", "").replace("```", "").strip()
        try:
            parsed = json.loads(cleaned)
            if isinstance(parsed, list) and all(isinstance(q, str) for q in parsed):
                return parsed
            logger.warning(
                "[RedTeam] Unexpected JSON structure from LLM. Falling back."
            )
        except json.JSONDecodeError as exc:
            logger.warning("[RedTeam] JSON parse error: %s | raw=%.80s", exc, raw_text)

        return SemanticCollector._lexical_fallback(original_queries)

    @staticmethod
    def _lexical_fallback(queries: list[str]) -> list[str]:
        """
        Мінімальний детермінований fallback для Red Teaming без LLM.
        Замінює найпоширеніші маркери дефіциту/загрози на їх антоніми.
        """
        replacements = {
            "дефіцит":      "надлишок",
            "нестача":      "постачання",
            "скорочення":   "розширення",
            "зупинка":      "відновлення",
            "збій":         "модернізація",
            "санкції":      "обхід санкцій",
            "провал":       "успіх",
            "shortage":     "surplus",
            "deficit":      "expansion",
            "decline":      "growth",
            "failure":      "recovery",
            "sanction":     "bypass",
            "crisis":       "stabilization",
        }
        counter_queries = []
        for q in queries:
            counter = q
            for bad, good in replacements.items():
                counter = counter.replace(bad, good)
            # Якщо заміни не відбулось — дописуємо нейтральний модифікатор
            if counter == q:
                counter = q + " розширення відновлення"
            counter_queries.append(counter)
        return counter_queries

    @staticmethod
    def _align_length(
        counter_dorks: list[str],
        original_queries: list[str],
    ) -> list[str]:
        """
        Вирівнює довжину списку контр-запитів до довжини оригінального списку.
        Зайві елементи обрізаються, відсутні доповнюються lexical_fallback.
        """
        aligned = list(counter_dorks)
        if len(aligned) > len(original_queries):
            aligned = aligned[: len(original_queries)]
        while len(aligned) < len(original_queries):
            missing_idx = len(aligned)
            fallback    = SemanticCollector._lexical_fallback(
                [original_queries[missing_idx]]
            )
            aligned.append(fallback[0])
        return aligned


# ─────────────────────────────────────────────────────────────────────────────
# Smoke-test (python semantic_collector.py)
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    from unittest.mock import MagicMock

    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s | %(levelname)-8s | %(message)s",
        datefmt="%H:%M:%S",
    )

    # ── Мок BrightDataClient ─────────────────────────────────────────────────
    mock_bd = MagicMock(spec=BrightDataClient)
    mock_bd.fetch_serp.return_value = [{
        "query":   "test",
        "status":  "ok",
        "results": [
            {"title": "Завод розширює виробництво", "url": "https://example.com/1",
             "snippet": "Виробничі потужності зросли на 15%.", "rank": 1},
        ],
        "raw": {},
    }]

    # ── Мок ReillyLlmRouter ──────────────────────────────────────────────────
    mock_router = MagicMock(spec=ReillyLlmRouter)
    mock_router.execute_query.return_value = json.dumps([
        'site:gov.ru "модернізація" "Уралвагонзавод" розширення 2024',
        '"ВПК" "вакансії" збільшення набір 2024',
    ], ensure_ascii=False)

    # ── Тестова ActionProgram (вихід Block 1) ────────────────────────────────
    test_program = {
        "raw_query": "Аналіз оборонної промисловості Росії 2024",
        "search_tasks": [
            {
                "search_type": "SEMANTIC",
                "bright_data_tool": "SERP_API",
                "priority": 1,
                "initial_queries": [
                    'site:gov.ru "тендер" "Уралвагонзавод" дефіцит 2024',
                    '"ВПК" "вакансії" скорочення 2024',
                ],
                "target_domains": ["MILITARY_SECURITY"],
            },
            {
                "search_type": "QUANTITATIVE",    # Має бути проігноровано
                "bright_data_tool": "Web_Scraper_API",
                "priority": 2,
                "initial_queries": ["Russian defense budget filetype:pdf"],
                "target_domains": ["ECONOMIC"],
            },
        ],
    }

    collector = SemanticCollector(
        bd_client=mock_bd,
        router=mock_router,
        cache_dir="./state/semantic_cache_test",
    )

    result = collector.collect_semantic_pipeline(
        action_program=test_program,
        country="ru",
        language="ru",
        save_cache=True,
    )

    print("\n" + "=" * 60)
    print("SEMANTIC COLLECTOR — SMOKE TEST OUTPUT")
    print("=" * 60)
    print(json.dumps(result, ensure_ascii=False, indent=2))

    pairs = result.get("semantic_data", [])
    print(f"\n✅ Dual-sweep pairs collected : {len(pairs)}")
    print(f"   Cache file                 : {result.get('cache_file', 'not saved')}")
    if pairs:
        print(f"   First pair direct results  : {len(pairs[0]['direct_results'])}")
        print(f"   First pair counter results : {len(pairs[0]['counter_results'])}")
